import { SSH } from '../types';
export { printCliTable } from './cli-table';
export * from './uuid';
export * from './qcloud-request';
export * from './http-request';
export * from './output';
export * from './function-packer';
export * from './store';
export * from './cloudbase-config';
export * from './auth';
export * from './check-auth';
export * from './os-release';
export declare function zipDir(dirPath: string, outputPath: string, ignore?: string | string[]): Promise<unknown>;
export declare function askForInput(question: any): Promise<string>;
export declare function getSSHConfig(): SSH;
export declare function getSSH(): Promise<SSH>;
